### ISSUE TITLE
remove the dashboard and add friend button from title bar and place them somewhere else.

### ISSUE THREAD

**Issue by Pranav2612000** [Pranav2612000/distrideochat#30]
Open to discussion.

**Comment by veddandekar** [comment]
Dashboard button can be added to the left panel at the top.
However, I'm of the opinion that the friend button could probably stay at the top, maybe just change it's design a bit instead.

**Comment by vasusharma7** [comment]
Why not do something like add a drop down on room and then there we can give add friend button ?

Also can this be done that a user creates a room but without adding any initial friend to that, just empty room and user then can add other friends ? Because the current structure doesn't support that I guess..I am not completely sure about it.

**Comment by vasusharma7** [comment]
![image](https://user-images.githubusercontent.com/40715071/82441515-a5d54200-9abb-11ea-9737-df3943ad3f1d.png)

**Comment by naman-modi** [comment]
'Invite Others' added to right subpanel.
